import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon } from '@heroicons/react/24/solid'

export default function Home() {
  return (
    <>
      <Head>
        <title>FlyBondi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-20 text-center">
        <h1 className="text-5xl ">
          Bienvenido a <b className="text-yellow-400">FlyBondi</b>
        </h1>
      </div>

      <div className="grid grid-cols-3 px-56">
        <Link href={"/cor"}>
          <div className="flex gap-6 border border-slate-400 rounded-xl p-4 hover:border-yellow-500">
            <h3 className="text-2xl font-semibold">COR</h3>
            <ArrowRightIcon width={24} />
          </div>
        </Link>
      </div>
    </>
  );
}
